version: "3.8"

services:
  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - tasknet

  app:
    build: ./backend
    image: task-manager-app
    container_name: task-manager-app
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - tasknet

volumes:
  pgdata:

networks:
  tasknet:
    driver: bridge

